# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_cuda_compilerNonecuda_compiler_versionNonepython3.10.____cpython:
        CONFIG: win_64_cuda_compilerNonecuda_compiler_versionNonepython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilerNonecuda_compil_h5e5be14d78
      win_64_cuda_compilerNonecuda_compiler_versionNonepython3.11.____cpython:
        CONFIG: win_64_cuda_compilerNonecuda_compiler_versionNonepython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilerNonecuda_compil_hefe9596428
      win_64_cuda_compilerNonecuda_compiler_versionNonepython3.12.____cpython:
        CONFIG: win_64_cuda_compilerNonecuda_compiler_versionNonepython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilerNonecuda_compil_h9b6735f038
      win_64_cuda_compilerNonecuda_compiler_versionNonepython3.13.____cp313:
        CONFIG: win_64_cuda_compilerNonecuda_compiler_versionNonepython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilerNonecuda_compil_hfe25655152
      win_64_cuda_compilerNonecuda_compiler_versionNonepython3.9.____cpython:
        CONFIG: win_64_cuda_compilerNonecuda_compiler_versionNonepython3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilerNonecuda_compil_h801dee6da8
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.10.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_h2bcc01ac80
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.11.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_h593b557b29
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.12.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_h4533b3b7f8
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.13.____cp313:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_h6bcc301db2
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.9.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.6python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_hc0474c0b55
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: C:\bld
    MINIFORGE_HOME: C:\Miniforge
    SET_PAGEFILE: 'True'
    UPLOAD_TEMP: D:\\tmp

  steps:

    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        MINIFORGE_HOME: $(MINIFORGE_HOME)
        CONDA_BLD_PATH: $(CONDA_BLD_PATH)
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
    - script: |
        set MINIFORGE_HOME=$(MINIFORGE_HOME)
        set CI=azure
        set CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        set FEEDSTOCK_NAME=$(build.Repository.Name)
        set ARTIFACT_STAGING_DIR=$(Build.ArtifactStagingDirectory)
        set CONDA_BLD_DIR=$(CONDA_BLD_PATH)
        set BLD_ARTIFACT_PREFIX=conda_artifacts
        if "%AGENT_JOBSTATUS%" == "Failed" (
            set ENV_ARTIFACT_PREFIX=conda_envs
        )
        call ".scripts\create_conda_build_artifacts.bat"
      displayName: Prepare conda build artifacts
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      displayName: Store conda build artifacts
      condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(BLD_ARTIFACT_PATH)
        artifactName: $(BLD_ARTIFACT_NAME)

    - task: PublishPipelineArtifact@1
      displayName: Store conda build environment artifacts
      condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(ENV_ARTIFACT_PATH)
        artifactName: $(ENV_ARTIFACT_NAME)